name: Check Markdown links

# Run on push, PRs, and every Sunday at 9 am
on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * 0"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
